### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by munees2tharun** [satelerd/Ketchapp-Bot#1]
Hi brother, is it possible to run this for a android game?

**Comment by satelerd** [comment]
Hi! Unfortunately this only works on the computer because the code is on python, but you can run the android game in a emulator and play it from the computer with the bot (maybe the code would require some simple modification).
Good luck.

**Comment by satelerd** [comment]
If you need any help don't doubt reaching me!

**Comment by munees2tharun** [comment]
Thank you brother,I hope you won't mind telling what kind of changes should be made.(I have no prior coding knowledge)

**Comment by satelerd** [comment]
If you would like to use this the easy way: 
1. Install files.
2. Install the libraries (cv2, pyautogui and time) through the cmd.
3. Modify some variables (from line 9 to 14) that depend on your computer directory and screen size.
4. Lastly, run the code (and move your mouse to the game screen).

I really don't have the time now to change the code to work on an emulator, but... Seeing your interest, I think this is a really good opportunity for you to learn how to code and contribute on GitHub!
This is an easy project, so if you want, I can give you a few resources that can help you understand the code so you can use it and contribute. Let me know.

**Comment by munees2tharun** [comment]
Than you brother, Really could use some assistance.what should i start with.

**Comment by satelerd** [comment]
I recommend you start by learning python; is a really great, versatile, and intuitive programing language (and the code for this project is on python).
I have some links to articles and courses that could be useful:
1. An introduction to programming: https://www.freecodecamp.org/news/a-gentler-introduction-to-programming-1f57383a1b2c/
2. Learn python: https://www.codecademy.com/learn/learn-python
3. Download Visual Studio Code, an IDE (try searching on youtube tutorials, I don't have one in mind, but there are plenty on yt)
4. Work on some easy projects that can motivate you... (like building a scraper or a simple game (maybe you can recreate a really simple version of wordle))
5. Learn how to Collab on Github: https://www.udemy.com/course/git-started-with-github/
6. (This should really be step 1!) Learn by yourself! Go watch tutorials on what you think you want and need to learn. Programming is a lot about learning how to learn and solve problems (you will encounter a lot of them) with google... So if you could learn something by yourself you can code whatever you want!

Some useful comments:
You will learn a lot more by actually doing things (building projects and solving the problems you encounter) rather than actually spending lots of time learning how to do things.
Yt and StackOverflow will be your best friends.
Here are some yt channels that helped me a ton: https://www.youtube.com/c/TechWithTim, https://www.youtube.com/c/Fireship, https://www.youtube.com/c/Freecodecamp

If you need help you can ask me! but always try to ask google first.

**Comment by Mohammedkalasha** [comment]
hi bro I run your code but when I move the mouse to the Screen it can't work

**Comment by satelerd** [comment]
You don't have to move the mouse, the code does it for you.

**Comment by Mohammedkalasha** [comment]
Bro can make a small video tutorial how this  ketachapp-bot  works please 🥺

**Comment by satelerd** [comment]
I have updated the readme tutorial... Write me if you need more help :)

**Comment by Mohammedkalasha** [comment]
Now it's work thank you 😄👍
